== Shared Concepts

=== Workshop: "`Achieving a shared understanding of concepts`"

Join us on the 13th and the 15th of April for an exchange of views on how to achieve a shared understanding of concepts - terminology and definitions - across domains.

==== Practical information

* Day 1: April 13, 2021, 3 hours from UTC 13:00
* Day 2: April 15, 2021, 3 hours from UTC 05:00

==== Purpose of the Workshop

Have you seen a term defined differently in one place from another?
Do you use or manage standardized terminologies/glossaries/thesauri?
How are these definitions mapped? Perhaps existing
terminologies/glossaries/thesauri can be made more useful in your
day-to-day work.

Many domains, such as geospatial, electro-technical, business and
telecommunications, and others maintain approved terms and
definitions through well-defined procedures, especially at
standardization bodies and consortia. We believe building
mutually-agreed links between concepts across domains would be
useful. How should we tie the concepts together, how can they be
maintained and  governed over time, and who is allowed to do so?

The workshop will focus on discussing a framework and procedures for
tackling these issues and work out any technical details at a later
time.

==== Organizers & Supporting Parties

The ISO/TC 211 Terminology Maintenance Group (TMG) is responsible
for matters relating to terminology within https://committee.iso.org/home/tc211[ISO/TC 211 Geographic information/Geomatics], which
includes the management, harmonization, and promotion of terminology
concepts, and their relationships in ISO/TC 211 deliverables. The
TMG coordinates and publishes a multi-lingual glossary of terms, see
https://github.com/ISO-TC211/TMG.


==== Registration and contacts

Please register at this form, or directly contact sharedconcepts@tc211tmg.org.

++++
<script type="text/javascript" src="https://form.jotform.com/jsform/210591038556052"></script>
++++
